"""Build a developer ``Floor Plan Engine.app`` for macOS.

The bundle is a thin launcher: it runs ``desktop.py`` with this project's
``.venv`` Python, so it always uses the current source tree and engine.
It is not a standalone, redistributable app — rebuild it if the project
folder moves.

    .venv/bin/python scripts/build_macos_app.py            # → dist/Floor Plan Engine.app
    .venv/bin/python scripts/build_macos_app.py --output ~/Applications
"""

from __future__ import annotations

import argparse
import plistlib
import shlex
import shutil
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path

import cv2
import numpy as np

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

from desktop import APP_NAME, BUNDLE_ID, ICON_PATH, LOG_HINT  # noqa: E402

EXECUTABLE = "floor-plan-engine"


def draw_icon(size: int = 1024) -> np.ndarray:
    """The Workbench brand mark (a floor-plan glyph) on a rounded navy tile."""
    scale = 4  # supersample for smooth edges
    s = size * scale
    image = np.zeros((s, s, 4), dtype=np.uint8)
    tile = np.zeros((s, s), dtype=np.uint8)
    inset, radius = int(s * 0.1), int(s * 0.18)
    a, b = inset, s - inset
    cv2.rectangle(tile, (a + radius, a), (b - radius, b), 255, -1)
    cv2.rectangle(tile, (a, a + radius), (b, b - radius), 255, -1)
    for cx, cy in ((a + radius, a + radius), (b - radius, a + radius), (a + radius, b - radius), (b - radius, b - radius)):
        cv2.circle(tile, (cx, cy), radius, 255, -1)
    image[tile > 0] = (61, 36, 19, 255)  # #13243d (BGR + alpha)

    # Glyph from the header SVG (viewBox 0..32), mapped into the tile.
    g0, g1 = a + (b - a) * 0.2, b - (b - a) * 0.2
    to_px = lambda v: int(round(g0 + (g1 - g0) * (v - 3) / 26))  # noqa: E731
    stroke = int((g1 - g0) * 3 / 26)
    white = (255, 255, 255, 255)
    cv2.rectangle(image, (to_px(3), to_px(3)), (to_px(29), to_px(29)), white, stroke, cv2.LINE_AA)
    for x1, y1, x2, y2 in ((3, 15, 13, 15), (13, 15, 13, 29), (13, 3, 13, 9), (19, 15, 29, 15), (19, 15, 19, 20)):
        cv2.line(image, (to_px(x1), to_px(y1)), (to_px(x2), to_px(y2)), white, stroke, cv2.LINE_AA)
    return cv2.resize(image, (size, size), interpolation=cv2.INTER_AREA)


def ensure_icon_png() -> Path:
    if not ICON_PATH.is_file():
        ICON_PATH.parent.mkdir(parents=True, exist_ok=True)
        cv2.imwrite(str(ICON_PATH), draw_icon())
    return ICON_PATH


def build_icns(png: Path, destination: Path) -> bool:
    """Convert the PNG to .icns with macOS's built-in sips + iconutil."""
    if not (shutil.which("sips") and shutil.which("iconutil")):
        return False
    with tempfile.TemporaryDirectory() as tmp:
        iconset = Path(tmp) / "AppIcon.iconset"
        iconset.mkdir()
        for points in (16, 32, 128, 256, 512):
            for factor, suffix in ((1, ""), (2, "@2x")):
                pixels = points * factor
                target = iconset / f"icon_{points}x{points}{suffix}.png"
                subprocess.run(["sips", "-z", str(pixels), str(pixels), str(png), "--out", str(target)],
                               check=True, capture_output=True)
        subprocess.run(["iconutil", "-c", "icns", str(iconset), "-o", str(destination)], check=True)
    return True


def launcher_script(project_root: Path) -> str:
    root = shlex.quote(str(project_root))
    log_dir = '"$HOME/Library/Logs/Floor Plan Engine"'
    return f"""#!/bin/bash
# Generated by scripts/build_macos_app.py — launches the Workbench from the project's .venv.
PROJECT_DIR={root}
PYTHON="$PROJECT_DIR/.venv/bin/python"
LOG_DIR={log_dir}
mkdir -p "$LOG_DIR"
# Finder starts apps with a minimal PATH; add Homebrew so Tesseract/Poppler are found.
export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
if [ ! -x "$PYTHON" ] || [ ! -f "$PROJECT_DIR/desktop.py" ]; then
  /usr/bin/osascript -e 'display alert "{APP_NAME}" message "Project or .venv not found at:\\n'"$PROJECT_DIR"'\\n\\nRebuild the app with scripts/build_macos_app.py." as critical'
  exit 1
fi
cd "$PROJECT_DIR" || exit 1
echo "--- $(date '+%Y-%m-%d %H:%M:%S') launching {APP_NAME}" >> "$LOG_DIR/desktop.log"
# LaunchServices may start a script-based app under Rosetta; the .venv's compiled
# packages (numpy, OpenCV, PyObjC) are native arm64, so run Python natively.
if [ "$(/usr/sbin/sysctl -n hw.optional.arm64 2>/dev/null)" = "1" ]; then
  exec /usr/bin/arch -arm64 "$PYTHON" "$PROJECT_DIR/desktop.py" >> "$LOG_DIR/desktop.log" 2>&1
fi
exec "$PYTHON" "$PROJECT_DIR/desktop.py" >> "$LOG_DIR/desktop.log" 2>&1
"""


def build(output_dir: Path) -> Path:
    version = tomllib.loads((PROJECT_ROOT / "pyproject.toml").read_text())["project"]["version"]
    app = output_dir / f"{APP_NAME}.app"
    if app.exists():
        shutil.rmtree(app)
    macos = app / "Contents" / "MacOS"
    resources = app / "Contents" / "Resources"
    macos.mkdir(parents=True)
    resources.mkdir(parents=True)

    executable = macos / EXECUTABLE
    executable.write_text(launcher_script(PROJECT_ROOT))
    executable.chmod(0o755)

    info = {
        "CFBundleName": APP_NAME,
        "CFBundleDisplayName": APP_NAME,
        "CFBundleIdentifier": BUNDLE_ID,
        "CFBundleExecutable": EXECUTABLE,
        "CFBundlePackageType": "APPL",
        "CFBundleShortVersionString": version,
        "CFBundleVersion": version,
        "CFBundleInfoDictionaryVersion": "6.0",
        "LSMinimumSystemVersion": "11.0",
        "LSArchitecturePriority": ["arm64", "x86_64"],
        "LSApplicationCategoryType": "public.app-category.developer-tools",
        "NSHighResolutionCapable": True,
    }
    if build_icns(ensure_icon_png(), resources / "AppIcon.icns"):
        info["CFBundleIconFile"] = "AppIcon"
    with (app / "Contents" / "Info.plist").open("wb") as handle:
        plistlib.dump(info, handle)
    return app


def main() -> int:
    parser = argparse.ArgumentParser(description=f"Build a developer {APP_NAME}.app")
    parser.add_argument("--output", type=Path, default=PROJECT_ROOT / "dist", help="folder to write the .app into")
    args = parser.parse_args()
    if sys.platform != "darwin":
        print("This builds a macOS .app; run it on macOS.", file=sys.stderr)
        return 1
    app = build(args.output.expanduser().resolve())
    print(f"Built: {app}")
    print(f"Logs:  {LOG_HINT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
